name: Loophole Tunnel
version: "1.2.5"
stage: stable
slug: ha-loophole-addon
apparmor: true
description: Home Assistant app for loophole.cloud tunneling to expose your HA instance with HTTPS over the public internet.
url: https://github.com/dasflaigsi/ha-supervisor-apps
arch:
  - amd64
  - aarch64
init: false
startup: services
boot: auto
host_network: true
homeassistant_api: true
options:
  port: 8123
  hostname: ""
  connectivity_check_interval: 15
  verbose: false
  logout_on_restart: false
schema:
  port: int(1,65535)
  hostname: str
  connectivity_check_interval: int(1,1440)
  verbose: bool
  logout_on_restart: bool
